using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace MS2027.ScriptSurveillance
{
    // IDE専用。Unityのコンパイルには登録しない。
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public sealed class CSED_SurveillanceAnalyzer : DiagnosticAnalyzer
    {
        private static DiagnosticDescriptor Rule(string id, string title, DiagnosticSeverity severity) =>
            new DiagnosticDescriptor(id, title, "{0}", "MS2027", severity, true);

        private static readonly DiagnosticDescriptor _unused = Rule("MS27001", "未使用の宣言", DiagnosticSeverity.Error);
        private static readonly DiagnosticDescriptor _recursive = Rule("MS27002", "プロパティの自己代入", DiagnosticSeverity.Error);
        private static readonly DiagnosticDescriptor _name = Rule("MS27101", "変数の命名規則", DiagnosticSeverity.Warning);
        private static readonly DiagnosticDescriptor _file = Rule("MS27102", "ファイルの接頭辞", DiagnosticSeverity.Warning);
        private static readonly DiagnosticDescriptor _frame = Rule("MS27103", "毎フレームの検索・ログ", DiagnosticSeverity.Warning);
        private static readonly DiagnosticDescriptor _size = Rule("MS27104", "コード量・ネスト", DiagnosticSeverity.Warning);
        private static readonly DiagnosticDescriptor _field = Rule("MS27105", "バッキングフィールドで公開", DiagnosticSeverity.Warning);

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
            ImmutableArray.Create(_unused, _recursive, _name, _file, _frame, _size, _field);

        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
            context.EnableConcurrentExecution();
            context.RegisterSemanticModelAction(AnalyzeModel);
            context.RegisterSyntaxNodeAction(AnalyzeVariable, SyntaxKind.VariableDeclarator,
                SyntaxKind.Parameter, SyntaxKind.ForEachStatement, SyntaxKind.SingleVariableDesignation);
            context.RegisterSyntaxNodeAction(AnalyzeType, SyntaxKind.ClassDeclaration, SyntaxKind.StructDeclaration,
                SyntaxKind.InterfaceDeclaration, SyntaxKind.EnumDeclaration);
            context.RegisterSyntaxNodeAction(AnalyzeMethod, SyntaxKind.MethodDeclaration,
                SyntaxKind.ConstructorDeclaration, SyntaxKind.GetAccessorDeclaration, SyntaxKind.SetAccessorDeclaration,
                SyntaxKind.LocalFunctionStatement);
            context.RegisterSyntaxNodeAction(AnalyzeCall, SyntaxKind.InvocationExpression);
            context.RegisterSyntaxNodeAction(AnalyzeAssignment, SyntaxKind.SimpleAssignmentExpression);
        }

        private static bool InScope(SyntaxTree tree)
        {
            string path = "/" + tree.FilePath.Replace('\\', '/');
            return path.IndexOf("/Assets/", StringComparison.OrdinalIgnoreCase) >= 0
                && path.IndexOf("/Assets/Plugins/", StringComparison.OrdinalIgnoreCase) < 0
                && path.IndexOf("/Assets/TutorialInfo/", StringComparison.OrdinalIgnoreCase) < 0
                && !path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
                && !path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
                && !tree.GetRoot().GetLeadingTrivia().ToFullString().Contains("<auto-generated");
        }

        private static void AnalyzeModel(SemanticModelAnalysisContext context)
        {
            if (!InScope(context.SemanticModel.SyntaxTree)) return;
            AnalyzeFields(context);
            // コンパイラーが解決したシンボルを使うため、別ファイル・拡張メソッドも考慮される。
            foreach (Diagnostic diagnostic in context.SemanticModel.GetDiagnostics(cancellationToken: context.CancellationToken))
            {
                if (diagnostic.IsSuppressed) continue;
                if (diagnostic.Id != "CS8019" && diagnostic.Id != "CS0168" && diagnostic.Id != "CS0219") continue;
                context.ReportDiagnostic(Diagnostic.Create(_unused, diagnostic.Location,
                    "未使用の using・変数です。必要性を確認してください。 (" + diagnostic.Id + ")"));
            }
        }

        private static void AnalyzeFields(SemanticModelAnalysisContext context)
        {
            // CompilationActionはVSの開いているファイルのみの解析では実行されない。
            // ドキュメント解析から全partial宣言を考慮したコンパイラー診断を取得し、
            // 現在のファイルの結果だけを報告する。別ファイルの結果を重複報告しない。
            foreach (Diagnostic diagnostic in context.SemanticModel.Compilation.GetDiagnostics(context.CancellationToken))
            {
                if (diagnostic.IsSuppressed || (diagnostic.Id != "CS0169" && diagnostic.Id != "CS0414")
                    || diagnostic.Location.SourceTree != context.SemanticModel.SyntaxTree) continue;
                SyntaxNode node = diagnostic.Location.SourceTree.GetRoot(context.CancellationToken)
                    .FindNode(diagnostic.Location.SourceSpan);
                VariableDeclaratorSyntax variable = node.AncestorsAndSelf().OfType<VariableDeclaratorSyntax>().FirstOrDefault();
                if (variable != null && context.SemanticModel
                    .GetDeclaredSymbol(variable, context.CancellationToken) is IFieldSymbol field)
                {
                    // SerializeField/SerializeReferenceや外部注入・リフレクション用の属性付きフィールドを保護。
                    if (field.GetAttributes().Length != 0 || field.ContainingType.GetAttributes().Any(
                        a => a.AttributeClass?.ToDisplayString() == "System.SerializableAttribute")) continue;
                }
                context.ReportDiagnostic(Diagnostic.Create(_unused, diagnostic.Location,
                    "未使用の using・変数です。必要性を確認してください。 (" + diagnostic.Id + ")"));
            }
        }

        private static void AnalyzeVariable(SyntaxNodeAnalysisContext context)
        {
            if (!InScope(context.Node.SyntaxTree)) return;
            ISymbol symbol = context.SemanticModel.GetDeclaredSymbol(context.Node, context.CancellationToken);
            if (symbol == null || symbol.Name == "_" || symbol.IsImplicitlyDeclared) return;
            if (!(symbol is ILocalSymbol) && !(symbol is IParameterSymbol) && !(symbol is IFieldSymbol)) return;
            IFieldSymbol field = symbol as IFieldSymbol;
            if (field?.ContainingType.TypeKind == TypeKind.Enum) return;
            bool prefix = field != null && (field.DeclaredAccessibility == Accessibility.Private
                || field.DeclaredAccessibility == Accessibility.Protected
                || field.DeclaredAccessibility == Accessibility.ProtectedOrInternal
                || field.DeclaredAccessibility == Accessibility.ProtectedAndInternal);
            string name = symbol.Name;
            string body = prefix && name.StartsWith("_", StringComparison.Ordinal) ? name.Substring(1) : name;
            bool valid = body.Length > 0 && char.IsLower(body[0]) && !body.Contains("_")
                && (!prefix || name.StartsWith("_", StringComparison.Ordinal));
            Location location = symbol.Locations.FirstOrDefault(l => l.IsInSource);
            if (!valid && location != null)
                context.ReportDiagnostic(Diagnostic.Create(_name, location,
                    name + " は " + (prefix ? "_lowerCamelCase" : "lowerCamelCase") + " にしてください。"));
            if (field != null && !field.IsConst && field.DeclaredAccessibility == Accessibility.Public)
                context.ReportDiagnostic(Diagnostic.Create(_field, location,
                    "公開フィールドは private のバッキングフィールドと => のプロパティで公開してください。"));
        }

        private static bool DerivesFrom(INamedTypeSymbol type, string fullName)
        {
            for (; type != null; type = type.BaseType)
                if (type.ToDisplayString() == fullName) return true;
            return false;
        }

        private static void AnalyzeType(SyntaxNodeAnalysisContext context)
        {
            if (!InScope(context.Node.SyntaxTree)) return;
            var declaration = (BaseTypeDeclarationSyntax)context.Node;
            int lines = LineCount(declaration);
            if (lines > 800)
                context.ReportDiagnostic(Diagnostic.Create(_size, declaration.Identifier.GetLocation(),
                    "型が " + lines + " 行あります。目安の800行以内に分割してください。"));
            // ファイルの代表となる最初のトップレベル型で一度だけ判定する。
            var first = declaration.SyntaxTree.GetRoot().DescendantNodes().OfType<BaseTypeDeclarationSyntax>().FirstOrDefault();
            if (declaration != first) return;
            var type = context.SemanticModel.GetDeclaredSymbol(declaration, context.CancellationToken) as INamedTypeSymbol;
            string path = declaration.SyntaxTree.FilePath.Replace('\\', '/');
            string prefix = ("/" + path).IndexOf("/Editor/", StringComparison.OrdinalIgnoreCase) >= 0
                || DerivesFrom(type, "UnityEditor.Editor") || DerivesFrom(type, "UnityEditor.EditorWindow") ? "CSED_"
                : type?.TypeKind == TypeKind.Enum ? "CSE_"
                : DerivesFrom(type, "UnityEngine.Rendering.VolumeComponent") ? "CSV_"
                : DerivesFrom(type, "UnityEngine.ScriptableObject") ? "CSO_" : "CS_";
            if (!Path.GetFileName(path).StartsWith(prefix, StringComparison.Ordinal))
                context.ReportDiagnostic(Diagnostic.Create(_file, declaration.Identifier.GetLocation(),
                    "ファイル名の先頭に " + prefix + " を付けてください。"));
        }

        private static int LineCount(SyntaxNode node)
        {
            FileLinePositionSpan span = node.GetLocation().GetLineSpan();
            return span.EndLinePosition.Line - span.StartLinePosition.Line + 1;
        }

        private static bool IsControl(SyntaxNode node) => node is IfStatementSyntax
            || node is ForStatementSyntax || node is ForEachStatementSyntax || node is WhileStatementSyntax
            || node is DoStatementSyntax || node is SwitchStatementSyntax || node is TryStatementSyntax
            || node is UsingStatementSyntax || node is LockStatementSyntax;

        private static void AnalyzeMethod(SyntaxNodeAnalysisContext context)
        {
            if (!InScope(context.Node.SyntaxTree)) return;
            int lines = LineCount(context.Node);
            Location location = context.Node.GetFirstToken().GetLocation();
            if (lines > 80) context.ReportDiagnostic(Diagnostic.Create(_size, location,
                "メソッド・アクセサーが " + lines + " 行あります。目安の80行以内に分割してください。"));
            foreach (SyntaxNode node in context.Node.DescendantNodes(n => !(n is LocalFunctionStatementSyntax)
                && !(n is AnonymousFunctionExpressionSyntax)).Where(IsControl))
            {
                // else ifは同じ分岐段階として数える。
                if (node is IfStatementSyntax && node.Parent is ElseClauseSyntax) continue;
                int depth = 1 + node.Ancestors().TakeWhile(a => a != context.Node).Count(a => IsControl(a)
                    && !(a is IfStatementSyntax && a.Parent is ElseClauseSyntax));
                if (depth == 4) context.ReportDiagnostic(Diagnostic.Create(_size, node.GetFirstToken().GetLocation(),
                    "制御構文のネストが3重を超えています。早期returnや関数分割を検討してください。"));
            }
        }

        private static void AnalyzeCall(SyntaxNodeAnalysisContext context)
        {
            if (!InScope(context.Node.SyntaxTree)) return;
            var method = context.Node.Ancestors().FirstOrDefault(n => n is MethodDeclarationSyntax
                || n is AnonymousFunctionExpressionSyntax || n is LocalFunctionStatementSyntax) as MethodDeclarationSyntax;
            if (method == null || (method.Identifier.ValueText != "Update" && method.Identifier.ValueText != "LateUpdate"
                && method.Identifier.ValueText != "FixedUpdate")) return;
            var owner = context.SemanticModel.GetDeclaredSymbol(method, context.CancellationToken);
            if (owner == null || owner.IsStatic || owner.Parameters.Length != 0 || !owner.ReturnsVoid
                || !DerivesFrom(owner.ContainingType, "UnityEngine.MonoBehaviour")) return;
            var called = context.SemanticModel.GetSymbolInfo(context.Node, context.CancellationToken).Symbol as IMethodSymbol;
            if (called == null) return;
            string type = called.ContainingType.ToDisplayString();
            bool find = type == "UnityEngine.GameObject" && (called.Name == "Find" || called.Name == "FindWithTag"
                || called.Name == "FindGameObjectWithTag" || called.Name == "FindGameObjectsWithTag")
                || type == "UnityEngine.Object" && called.Name.StartsWith("FindObject", StringComparison.Ordinal);
            bool log = type == "UnityEngine.Debug" && called.Name.StartsWith("Log", StringComparison.Ordinal);
            if (find || log) context.ReportDiagnostic(Diagnostic.Create(_frame, context.Node.GetLocation(),
                "毎フレーム呼ばれる " + method.Identifier.ValueText + " 内の " + called.Name
                + " です。検索結果のキャッシュ・ログの削除や実行頻度の見直しを検討してください。"));
        }

        private static void AnalyzeAssignment(SyntaxNodeAnalysisContext context)
        {
            if (!InScope(context.Node.SyntaxTree)) return;
            var assignment = (AssignmentExpressionSyntax)context.Node;
            var accessor = assignment.Ancestors().OfType<AccessorDeclarationSyntax>().FirstOrDefault();
            if (accessor == null || !accessor.IsKind(SyntaxKind.SetAccessorDeclaration)
                || assignment.Ancestors().TakeWhile(n => n != accessor).Any(n => n is AnonymousFunctionExpressionSyntax
                    || n is LocalFunctionStatementSyntax)) return;
            var property = accessor.Parent?.Parent as PropertyDeclarationSyntax;
            if (property == null) return;
            // 別インスタンスの同じプロパティへの代入は正常。
            if (!(assignment.Left is IdentifierNameSyntax)
                && !(assignment.Left is MemberAccessExpressionSyntax member && member.Expression is ThisExpressionSyntax)) return;
            if (SymbolEqualityComparer.Default.Equals(context.SemanticModel.GetSymbolInfo(assignment.Left).Symbol,
                context.SemanticModel.GetDeclaredSymbol(property)))
                context.ReportDiagnostic(Diagnostic.Create(_recursive, assignment.Left.GetLocation(),
                    "setterが同じプロパティを呼び続けます。バッキングフィールドへ代入してください。"));
        }
    }
}
